name: Init CI

on:
  pull_request_target:

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Comment on PR
        uses: harupy/comment-on-pr@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: welcome_pr.md
